version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://root:123456@db:5432/dbtest
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbtest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
