services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://root:123456@db:5432/dbtest
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbtest
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080
    depends_on:
      - web
  ngrok:
      image: wernight/ngrok
      ports:
        - "8081:8081" #just a diagnosis port
      command:
        - /bin/sh
        - -c
        - |
          ngrok start --all
      volumes:
        - .:/home/ngrok/.ngrok2/
      depends_on:
        - jenkins
      environment:
        - NGROK_AUTH_TOKEN="2npivnXMYn42sKHzVwlRrksyUyX_5K5QpDRbB9k6i1UJFim6o"
      networks:
        - main-internal-net

networks:
  main-internal-net:
    driver: bridge
volumes:
  postgres_data:
  jenkins_home:
